application: reportergame
version: 1
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py
  
- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /img
  static_dir: img

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: /.*
  script: main.py

  
builtins:
- remote_api: on
- datastore_admin: on