# This Python file uses the following encoding: utf-8

truefalse_fr_facturation_tarification = {
	'instruction': 'Retweetez toutes les propositions qui sont vraies.',
	'items': [
		'Toutes les factures qui concernent la vente d’un même produit au cours d’un même mois doivent comporter le même numéro de facture et la même date de facturation.',
		'Sur les factures, il n’est pas nécessaire de noter les modalités de paiement.', 
		'Il suffit d’indiquer le montant hors TVA et le montant TVA comprise sur la facture sans différencier les différents taux appliqués.', 
		'La date de facturation est facultative.', 
		'Si la TVA n’est pas due sur une certaine opération commerciale, il faut le justifier en mentionnant le texte légal y afférent.', 
		'Seuls le montant total et la dénomination de l’article doivent figurer sur la facture.', 
		'Toutes les factures doivent être établies en trois exemplaires : un exemplaire pour le comptable du vendeur, un pour l’acheteur et un pour l’administration fiscale.', 
		'Les factures électroniques ne sont pas des factures reconnues légalement. Il faut toujours conserver une version papier.', 
		'Il faut toujours remettre une facture lors de la vente de marchandises.',
		'Il ne faut pas établir de facture lorsqu’il s’agit d’une prestation de services effectuée dans un autre Etat membre de l’Union européenne.',
	]
}

truefalse_en_countable_uncountable = {
	'instruction': 'Retweet countable nouns only.',
	'items': [
		{'value':1, 'text':'crowd'},
		{'value':1, 'text':'elderly'},
		{'value':1, 'text':'season'},
		{'value':1, 'text':'moment'},
		{'value':1, 'text':'day'},
		{'value':1, 'text':'culprit'},
		{'value':1, 'text':'greenhouse'},
		{'value':1, 'text':'payment'},
		{'value':1, 'text':'flavour'},
		{'value':1, 'text':'stain'},
		{'value':1, 'text':'key'},
		{'value':1, 'text':'foot'},
		{'value':1, 'text':'adult'},
		{'value':1, 'text':'ski'},
		{'value':1, 'text':'boot'},
		{'value':1, 'text':'bike'},
		{'value':1, 'text':'vehicle'},
		{'value':1, 'text':'mirror'},
		{'value':-1, 'text':'luggage'}, 
		{'value':-1, 'text':'equipment'}, 
		{'value':-1, 'text':'furniture'}, 
		{'value':-1, 'text':'experience'}, 
		{'value':-1, 'text':'applause'}, 
		{'value':-1, 'text':'photography'}, 
		{'value':-1, 'text':'traffic'}, 
		{'value':-1, 'text':'harm'}, 
		{'value':-1, 'text':'publicity'}, 
		{'value':-1, 'text':'homework'}, 
		{'value':-1, 'text':'wood'}, 
		{'value':-1, 'text':'cloth'}, 
		{'value':-1, 'text':'ice'}, 
		{'value':-1, 'text':'plastic'}, 
		{'value':-1, 'text':'wool'}, 
		{'value':-1, 'text':'steel'}, 
		{'value':-1, 'text':'aluminium'}, 
		{'value':-1, 'text':'metal'}, 
		{'value':-1, 'text':'glass'}, 
		{'value':-1, 'text':'leather'}, 
		{'value':-1, 'text':'water'}, 
		{'value':-1, 'text':'milk'}, 
		{'value':-1, 'text':'wine'}, 
		{'value':-1, 'text':'beer'}, 
		{'value':-1, 'text':'cake'}, 
		{'value':-1, 'text':'sugar'}, 
		{'value':-1, 'text':'rice'}, 
		{'value':-1, 'text':'meat'}, 
		{'value':-1, 'text':'cheese'}, 
		{'value':-1, 'text':'flour'}, 
	]
}